version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      
