version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=calorieDB
