name: CI/CD Pipeline for Flask App

on:
  push:
    branches: [ main, master ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, closed]
    paths:
      - 'app/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pymongo

      - name: Run tests
        env:
          MONGO_URI: mongodb://localhost:27017/test
        run: |
          # Assuming you have a script to run tests
          python -m unittest discover -s tests

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flaskapp:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Digital Ocean
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          SSH_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST <<-EOF
            docker pull $DOCKER_USERNAME/flaskapp:latest
            docker stop web || true
            docker rm web || true
            docker run -d --name web -p 80:5000 $DOCKER_USERNAME/flaskapp:latest
          EOF
