name: App CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - deployment
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set Environment Variables
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
        echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> $GITHUB_ENV
        echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pip install pytest pytest-cov
        pytest --cov=./

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }} -f app/Dockerfile app

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}

    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        password: ${{ secrets.DROPLET_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}
          docker-compose -f root/myapp/docker-compose.yml up -d
